### ISSUE TITLE
GlobalAutoloadGenerator::getPathCode can give a Fatal error 

### ISSUE THREAD

**Issue by thamrx** [iwink/composer-global-installer#11]
**Describe the bug**
```
PHP Fatal error:  Uncaught TypeError: strpos() expects parameter 1 to be string, bool given in /var/composer/vendor/iwink/composer-global-installer/src/GlobalAutoloadGenerator.php:92
Stack trace:
#0 /var/composer/vendor/iwink/composer-global-installer/src/GlobalAutoloadGenerator.php(92): strpos(false, '/usr/local/lib/...')
#1 phar:///usr/local/bin/composer/src/Composer/Autoload/AutoloadGenerator.php(245): Iwink\ComposerGlobalInstaller\GlobalAutoloadGenerator->getPathCode(Object(Composer\Util\Filesystem), '/data/projects/...', '/data/projects/...', 'src/Controller')
#2 /var/composer/vendor/iwink/composer-global-installer/src/GlobalAutoloadGenerator.php(71): Composer\Autoload\AutoloadGenerator->dump(Object(Composer\Config), Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Package\RootPackage), Object(Composer\Installer\InstallationManager), '/data/projects/...', false, '')
#3 phar:///usr/local/bin/composer/src/Composer/Installer.php(309): Iwink\ComposerGlobalInstaller\GlobalAutoloadGenerator->dump(Objec in /var/composer/vendor/iwink/composer-global-installer/src/GlobalAutoloadGenerator.php on line 92
```

**To Reproduce**
Put a non existing path in `composer.json` of your project. i.e: 
```
"autoload": {
    "psr-4": {
        "Test123\\": "src/Test123"
    }
},
```

**Expected behavior**
No fatal error, throw an Exception with more detailed info on why the script failed.

**Additional context**
https://github.com/iwink/composer-global-installer/blob/18aada27b39ad89911111f99cdb6056129a53a7b/src/GlobalAutoloadGenerator.php#L90-L92

`$resolvedPath` will be `false` in this case and you will get the the error as seen above.

**Comment by danielkoster** [comment]
Could you use the issue-template provided, or provide a reproduction-scenario on how to reproduce this error? Thanks in advance!

**Comment by danielkoster** [comment]
Papertrail: a non-existing directory was provided in this project's `composer.json`. The error which was shown was not very informative. That's why I created #12.
